# Site settings
name: Rizky Ramadhan
title: Rizky Ramadhan | Web Developer
description: A guy who creating advanced web applications with elegant designs and solid code
url: https://jmiryas.github.io/
baseurl: ''
email: jmiryasg@gmail.com
cover: https://jmiryas.github.io/img/og.png
logo: https://jmiryas.github.io/img/emojis/technologist.png
resume: https://jmiryas.github.io/resume.pdf
social:
  - title: email
    url: mailto:jmiryas@gmail.com
  - title: github
    url: https://github.com/jmiryas
  - title: linkedin
    url: https://www.linkedin.com/in/rizky-ramadhan-7418b6268/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
